### ISSUE TITLE
Thunderbird 102.2.0 Error ( Snap / Flatpak discussion)

### ISSUE THREAD

**Issue by awrski** [electrotype/thunderbird-addon-scriptable-notifications#1]
Everything installed as advised, but debugging shows

"ExtensionError: No such native application scriptableNotifications"

for the simple notification script.

What's wrong?

**Comment by electrotype** [comment]
What plateform are you on?

Maybe have a look at where the generated manifest can be saved: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests#manifest_location

I only tried my extension on Linux Manjaro KDE and Windows 10, so any feedback for other plateforms is welcome.

**Comment by awrski** [comment]
Hi,

Platform is

KDE neon 5.25, Kernel 5.19.1

Manifest is stored analog to your advices at

~/.mozilla/native-messaging-hosts/scriptableNotifications.json

Thunderbird ist 102.2.0 Snap version. May be the path is invalid, but what is correct for that installation?

**Comment by electrotype** [comment]
I did try with the Snap version of Thunderbird and I have the same error as you.

I don't know how to fix this issue, sorry. 

I'll add a note to the documentation saying that it may not work with a Snap version.

**Comment by awrski** [comment]
Ok, it's a pitty but thanks for your support.

**Comment by awrski** [comment]
I removed the Snap version and installed the flatpak version, same issue!

**Comment by electrotype** [comment]
Have you tried the regular version? Just to see if it would work?

I'm not very familiar with formats like Snap/Flatpack and their security model/features. I know there are some paths restrictions, but I would have though anything under `~`would have worked properly. Oh well... Maybe someday someone will find a solution. I'll make sure to update this thread then.

**Comment by electrotype** [comment]
I found some information. I don't think Native Messaging is currently supported _at all_ on applications packaged as Snap or Flatpak, sadly.

https://forum.snapcraft.io/t/native-messaging-support-in-strictly-confined-browser-snaps/26849/5

https://github.com/flatpak/xdg-desktop-portal/issues/655

**Comment by awrski** [comment]
I removed Flatpak version too and installed native Thunderbird 102.2.0.

Now I get this messages:

Failed to execute command "/home/andre/scripts/thunderbird/script.sh"
Error: Attempt to postMessage on disconnected port

**Comment by electrotype** [comment]
I have no idea, sorry. 
"It works on my machine", lol.

**Comment by awrski** [comment]
Have you installed the gnome shell?

**Comment by electrotype** [comment]
I have no idea what you're talking about, so probably "no".

**Comment by awrski** [comment]
Ok, I think you are not a real developer, right?

**Comment by awrski** [comment]
no ideas but in a snit, wow

**Comment by sidamos** [comment]
I am on Mac and also get "No such native application scriptableNotifications".

**Comment by electrotype** [comment]
I can't reproduce as I have no access to a Mac. Maybe the instructions on where to place the Manifest are incorrect? If you find the correct location please advise and I'll update the documentation.

**Comment by sidamos** [comment]
According to Mozilla docs, the location and name of the Manifest are correct for Mac.
