### ISSUE TITLE
Send msg URI in extended info?

### ISSUE THREAD

**Issue by kupietools** [electrotype/thunderbird-addon-scriptable-notifications#12]
I previously used Mailbox Alert, the developer of which says is not likely to be updated to 115, to call TerminalNotifier <https://github.com/julienXX/terminal-notifier> on my Mac. Actually I had Mailbox Alert call a bash script, which read the parameters sent by Mailbox Alert and formatted them for TerminalNotifier. I think I can write a bridge that will take Scriptable Nofications's JSON and transform it for the same use. 

One thing is missing though: Mailbox Alert sent a TB Message URI, which meant I was able to make TerminalNotifier's notifications clickable... clicking an OS notification would directly open the message in Thunderbird, no muss, no fuss. I don't know anything about the under-the-hood changes in 115, but, do message URIs still exist, and would they be an easy bit of info to include in the JSON? 

Perhaps someone might find Folder URIs of use, too.

**Comment by electrotype** [comment]
Hi,

@sphh is the one who implemented the "complex" flow. He may be the best person to answer you.... I only use the simple mode, so I prefer not to touch the complex one, if possible.

PRs are welcome if you want to try it yourself!

Otherwise, I might take the time to check it out when I have some time.

**Comment by sphh** [comment]
@kupietools: Could you please give an example of a message (and a folder) URI please?

Do you also happen to know, how to get them from the [`MessageHeader`](https://webextension-api.thunderbird.net/en/latest/messages.html#messages-messageheader) (and [`MailFolder`](https://webextension-api.thunderbird.net/en/latest/folders.html#folders-mailfolder) object? Then it should be fairly easy to add these URIs to the payload. The above linked documentation for `MessageHeader` and `MailFolder` do not mention any URIs.

**Comment by electrotype** [comment]
Closing since information is missing. Feel free to ask for it to be reopened.
