### ISSUE TITLE
Samples do not work

### ISSUE THREAD

**Issue by BruceDenney** [electrotype/thunderbird-addon-scriptable-notifications#13]
Hi the windows simple sample does not work with python 3 as the tk stuff has changed

**Comment by electrotype** [comment]
Thanks for the report. I'll have a look as soon as I can.

**Comment by electrotype** [comment]
Windows simple script updated and is hopefully working. It is still very, very basic but at least it works and can be used as a starting point for something more complex.

https://github.com/electrotype/thunderbird-addon-scriptable-notifications/blob/main/scriptExamples/simpleMode/windows-simple/simpleNotification.py

Will be available in the next 5.5 release of the extension.
