### ISSUE TITLE
This does not appear to work on my Mac (M2 processor)

### ISSUE THREAD

**Issue by crotalis** [electrotype/thunderbird-addon-scriptable-notifications#14]
### No indication that the script is executed. I have it write to a log file, with nothing there.

macOS Sonoma 14.2.1

Thanks.

**Comment by electrotype** [comment]
More than one person has contacted me saying that the addon doesn't work on their Mac. I do not have access to a Mac to test.

If anyone with a Mac is able to get the addon to work, please let me know if there's anything special you need to do to get it to work, and I'll update the documentation...

For now, I'll add a warning that the addon may not work on Mac.

**Comment by tech189** [comment]
I found a fix, it seems like Thunderbird looks for manifests in `~/Library/Mozilla/NativeMessagingHosts/` rather than `~/Library/Application Support/Mozilla/NativeMessagingHosts/`. Please check out my PR!

**Comment by electrotype** [comment]
Let's leave this issue open for a while in case the fix doesn't work for all Mac users.

Thanks for the PR @tech189 !

**Comment by electrotype** [comment]
Version 6.0 has been submitted to the Thunderbird addons site and will be available soon:

https://addons.thunderbird.net/en-US/thunderbird/addon/scriptable-notifications
