### ISSUE TITLE
Bash script to notify-send the Email-Subject

### ISSUE THREAD

**Issue by ThomasSeeker** [electrotype/thunderbird-addon-scriptable-notifications#16]
Hey there, 

is it possible to notify-send the email-subject via a bash script in the extended mode? 
How could this look like?

PS: I'm on Kubuntu.

**Comment by electrotype** [comment]
Hi. 

Bash scripts don't work well with the extended mode. I don't know how to parse complex data coming from stdin with bash. It's probably better for you to stick to the Python example, and modify it to call `notify-send` in a subprocess, if that's what you really want to do.

Good luck.

**Comment by ThomasSeeker** [comment]
Thank you electrotype!

Unfortunately I have no python skills at all.

So now I use the script-connectionless.py to write the log. And I let it also start a bash script via this addition:

`import subprocess
rc = subprocess.call("/path/to/bash/script/name.bash")`

And then read the log with this bash script and do my limited magic there.

Thank you for this wonderful addon!
:-)
