### ISSUE TITLE
rss

### ISSUE THREAD

**Issue by clumsyfingers** [electrotype/thunderbird-addon-scriptable-notifications#2]
great extension. is it possible to make it work for rss feed accounts as well? (you'll find it in account settings > account actions>add feed account, in case you didnt know)

also, any chance you could add a script example for showing icon1 when there are no new messages, and icon2 when there are new messages (and back to icon1 again when the new message(s) are marked read? i quite dislike new icons popping up in the tray and moving things around so always having an icon is better imo

thanks for this extensions, its pretty great

**Comment by electrotype** [comment]
Adding Feeds as an "inbox" is a good idea, I'll see what I can do!

For the script examples, sadly it would be endless if I started to write one for every need... It is actually the goal of this add-on to give each user the possibility to write his own!

But I'm of course open to pull requests to add interesting examples.

Thanks for the kind words.

**Comment by electrotype** [comment]
I added support for "Feeds" accounts.

Before I release the change, could you please try the _master_ branch, with your own feeds, to see if they work properly?
Just uninstall the add-on, restart Thunderbird and follow the "Installation / From Source" section:
https://github.com/electrotype/thunderbird-addon-scriptable-notifications#from-source

**Comment by clumsyfingers** [comment]
hey
seems to work well as far as i can see :)
thanks

**Comment by electrotype** [comment]
Thanks for your test. 
Version 3 released with support for Feeds accounts.
